from pydantic import BaseModel

class DppConfig(BaseModel):
    """
    Configuration for DPP (Data Processing Pipeline).
    """
    difficulty: str="medium"
    style_notes: str="multiple_choice"
    n_questions: int=10

    #Handle pdf layout
    title:str="Practice Questions"
    include_explainations:bool=True
    footer_text:str="Generated by Veda"

_current_config: DppConfig = DppConfig()

def get_config() -> DppConfig:
    """
    Get the current DPP configuration.
    """
    return _current_config

def update_config(new_config: DppConfig)-> DppConfig:
    """
    Update the current DPP configuration.
    """
    global _current_config
    _current_config = new_config
    return _current_config
